/* eslint-disable no-undef */
const express = require('express');
const path = require('path');
const app = express();

// Serve the static files from the dist folder (generated by Vite)
app.use(express.static(path.join(__dirname, 'dist')));

// Catch-all route for SPA routing
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Listen on the appropriate port (Heroku uses process.env.PORT)
const port = process.env.PORT || 5000;
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});

